### ISSUE TITLE
Add support for SonfConf conference format

### ISSUE THREAD

**Issue by madanalogy** [CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g11#5]
Support importing of data in SoftConf format and creation of presentations for this conference format
- [x] Frontend: Add SoftConf presentation support (importing GUI already available)
- [x] Backend (Import): Support persistence of SoftConf data import in the database
- [x] Backend (Presentation): Add support for analysis requests for data in SoftConf format
