### ISSUE TITLE
Improve web application UI

### ISSUE THREAD

**Issue by madanalogy** [CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g11#7]
Current proposed improvements:
- [x] Make workflow more intuitive, improve the user menu
- [x] Combine the conference date data and conference csv persistence data
- [x] Allow help page access without login
